# Generated by Django 4.2.20 on 2025-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rozet Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkon Sınıfı')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Resim URL')),
                ('points_required', models.IntegerField(blank=True, null=True, verbose_name='Gereken Puan')),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, to='core.badge', verbose_name='Kazanılan Rozetler'),
        ),
    ]
