# Generated by Django 4.2.20 on 2025-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_badge_user_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='comment_count_required',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gereken Yorum Sayısı'),
        ),
    ]
