# Generated by Django 4.2.20 on 2025-04-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_badge_comment_count_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Sohbet Başlığı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Chatbot Sohbeti',
                'verbose_name_plural': 'Chatbot Sohbetleri',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Kullanıcı'), ('assistant', 'Filmbot')], max_length=10, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatbotconversation', verbose_name='Sohbet')),
            ],
            options={
                'verbose_name': 'Sohbet Mesajı',
                'verbose_name_plural': 'Sohbet Mesajları',
                'ordering': ['timestamp'],
            },
        ),
    ]
