# Generated by Django 4.2.20 on 2025-04-28 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatbotconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_episode', 'Yeni Bölüm'), ('sequel', 'Devam Filmi'), ('new_trailer', 'Yeni Fragman'), ('release_date', 'Çıkış Tarihi'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Bildirim Türü')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Bildirim Metni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.media', verbose_name='Medya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation',
        ),
        migrations.AlterField(
            model_name='userlist',
            name='list_type',
            field=models.CharField(choices=[('watched', 'İzledim'), ('watchlist', 'İzlenecekler'), ('favorite', 'Favoriler'), ('follow', 'Takip Listesi')], max_length=10, verbose_name='Liste Türü'),
        ),
        migrations.DeleteModel(
            name='ChatbotConversation',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
