# Generated by Django 4.2.20 on 2025-04-28 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250428_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Yeni Sohbet', max_length=200, verbose_name='Sohbet Başlığı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlama Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Mesaj Zamanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sohbet Konuşması',
                'verbose_name_plural': 'Sohbet Konuşmaları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Bildirim Linki'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Yorum İçeriği'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.media', verbose_name='İlgili Medya'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Bildirim Mesajı'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='list_type',
            field=models.CharField(choices=[('favorite', 'Favoriler'), ('watchlist', 'İzlenecekler'), ('follow', 'Takip Listesi')], max_length=10, verbose_name='Liste Türü'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is_user', models.BooleanField(default=True, verbose_name='Gönderen Kullanıcı mı?')),
                ('text', models.TextField(verbose_name='Mesaj İçeriği')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Zamanı')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatconversation', verbose_name='Konuşma')),
            ],
            options={
                'verbose_name': 'Sohbet Mesajı',
                'verbose_name_plural': 'Sohbet Mesajları',
                'ordering': ['sent_at'],
            },
        ),
    ]
