# Generated by Django 4.2.20 on 2025-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chatconversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='recommendations_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Öneri Verisi (JSON)'),
        ),
    ]
