# Generated by Django 4.2.20 on 2025-04-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatmessage_recommendations_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster Yolu'),
        ),
    ]
