# Generated by Django 4.2.20 on 2025-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_media_poster_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Rozet', 'verbose_name_plural': 'Rozetler'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='image_url',
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('engagement', 'Etkileşim'), ('collection', 'Koleksiyon'), ('community', 'Topluluk'), ('special', 'Özel')], default='special', max_length=50, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badge_icons/', verbose_name='Rozet İkonu'),
        ),
    ]
