# Generated by Django 4.2.20 on 2025-05-01 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_badge_options_remove_badge_icon_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Film'), ('tv', 'Dizi')], max_length=5),
        ),
        migrations.AlterField(
            model_name='media',
            name='tmdb_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Puanlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puan (1-10)'),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('tmdb_id', 'media_type')},
        ),
    ]
