# Generated by Django 4.2.20 on 2025-05-01 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_media_options_alter_media_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHiddenConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True, verbose_name='Gizlenme Zamanı')),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_hidden_by', to=settings.AUTH_USER_MODEL, verbose_name='Sohbetin Diğer Kullanıcısı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Gizleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Gizlenen Sohbet',
                'verbose_name_plural': 'Gizlenen Sohbetler',
                'ordering': ['-hidden_at'],
                'unique_together': {('user', 'other_user')},
            },
        ),
    ]
