# Generated by Django 4.2.20 on 2025-05-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userhiddenconversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['category', 'tier', 'name'], 'verbose_name': 'Rozet', 'verbose_name_plural': 'Rozetler'},
        ),
        migrations.AddField(
            model_name='badge',
            name='favorites_count_required',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gereken Favori Sayısı'),
        ),
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='badge',
            name='ratings_count_required',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gereken Puanlama Sayısı'),
        ),
        migrations.AddField(
            model_name='badge',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronz'), ('silver', 'Gümüş'), ('gold', 'Altın')], default='bronze', max_length=10, verbose_name='Seviye'),
        ),
    ]
