# Generated by Django 4.2.20 on 2025-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_badge_options_badge_favorites_count_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['category', 'tier_order', 'name'], 'verbose_name': 'Rozet', 'verbose_name_plural': 'Rozetler'},
        ),
        migrations.AddField(
            model_name='badge',
            name='followers_count_required',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gereken Takipçi Sayısı'),
        ),
        migrations.AddField(
            model_name='badge',
            name='following_count_required',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gereken Takip Sayısı'),
        ),
        migrations.AddField(
            model_name='badge',
            name='tier_order',
            field=models.IntegerField(default=1, verbose_name='Seviye Sırası'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('rating', 'Puanlama'), ('commenting', 'Yorumlama'), ('collection', 'Koleksiyon'), ('social', 'Sosyal'), ('community', 'Topluluk'), ('special', 'Özel')], default='special', max_length=50, verbose_name='Kategori'),
        ),
    ]
