from django.urls import path
from .views import (
    SignUpView, UserProfileView, SearchView, PopularMediaView, MediaDetailView,
    UpdateUserListView,
    add_comment_view,
    RateMediaView,
    ChatbotView,
    ChatSendMessageView,
    StreamingChatView,
    ToggleFollowView,
    UserProfileUpdateView,
    InboxView,
    ConversationView,
    NotificationsView,
    LoadChatMessagesView,
    DeleteChatConversationView,
    RenameChatConversationView,
    CheckUserExistsAPIView,
    DeleteMessageConversationView,
    FollowersListView,
    FollowingListView,
    BadgesListView,
    RefreshAISuggestionView
)

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/<str:username>/', UserProfileView.as_view(), name='user_profile'),
    path('profile/<str:username>/followers/', FollowersListView.as_view(), name='followers_list'),
    path('profile/<str:username>/following/', FollowingListView.as_view(), name='following_list'),
    path('badges/', BadgesListView.as_view(), name='badges_list'),
    path('catalog/', PopularMediaView.as_view(), name='catalog'),
    path('media/<str:media_type>/<int:media_id>/', MediaDetailView.as_view(), name='media_detail'),
    path('list/update/', UpdateUserListView.as_view(), name='list_update'),
    path('comment/add/<int:media_id>/', add_comment_view, name='add_comment'),
    path('rate/update/', RateMediaView.as_view(), name='rate_update'),
    path('chatbot/', ChatbotView.as_view(), name='chatbot'),
    path('chatbot/send_message/', ChatSendMessageView.as_view(), name='chatbot_send_message'),
    path('chatbot/stream/', StreamingChatView.as_view(), name='chatbot_stream'),
    path('follow/toggle/', ToggleFollowView.as_view(), name='toggle_follow'),
    path('messages/', InboxView.as_view(), name='inbox'),
    path('messages/<str:username>/', ConversationView.as_view(), name='conversation'),
    path('messages/<str:username>/delete/', DeleteMessageConversationView.as_view(), name='delete_message_conversation'),
    path('notifications/', NotificationsView.as_view(), name='notifications'),
    path('chatbot/conversation/<int:conversation_id>/', LoadChatMessagesView.as_view(), name='chatbot_load_messages'),
    path('chatbot/conversation/<int:conversation_id>/delete/', DeleteChatConversationView.as_view(), name='chatbot_delete_conversation'),
    path('chatbot/conversation/<int:conversation_id>/rename/', RenameChatConversationView.as_view(), name='chatbot_rename_conversation'),
    path('api/user/check/<str:username>/', CheckUserExistsAPIView.as_view(), name='api_check_user_exists'),
    path('search/refresh_ai/', RefreshAISuggestionView.as_view(), name='search_refresh_ai'),
] 